package com.neil.pojo;

public class Administrator {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column administrator.account
	 * @mbg.generated  Sat Jun 17 21:27:32 CST 2017
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column administrator.name
	 * @mbg.generated  Sat Jun 17 21:27:32 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column administrator.password
	 * @mbg.generated  Sat Jun 17 21:27:32 CST 2017
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column administrator.account
	 * @return  the value of administrator.account
	 * @mbg.generated  Sat Jun 17 21:27:32 CST 2017
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column administrator.account
	 * @param account  the value for administrator.account
	 * @mbg.generated  Sat Jun 17 21:27:32 CST 2017
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column administrator.name
	 * @return  the value of administrator.name
	 * @mbg.generated  Sat Jun 17 21:27:32 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column administrator.name
	 * @param name  the value for administrator.name
	 * @mbg.generated  Sat Jun 17 21:27:32 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column administrator.password
	 * @return  the value of administrator.password
	 * @mbg.generated  Sat Jun 17 21:27:32 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column administrator.password
	 * @param password  the value for administrator.password
	 * @mbg.generated  Sat Jun 17 21:27:32 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}