package com.neil.pojo;

public class Course {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column course.Cno
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	private String cno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column course.Cname
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	private String cname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column course.Tno
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	private String tno;

	private Teacher teacher;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.Cno
	 * 
	 * @return the value of course.Cno
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public String getCno() {
		return cno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.Cno
	 * 
	 * @param cno
	 *            the value for course.Cno
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public void setCno(String cno) {
		this.cno = cno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.Cname
	 * 
	 * @return the value of course.Cname
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.Cname
	 * 
	 * @param cname
	 *            the value for course.Cname
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public void setCname(String cname) {
		this.cname = cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column course.Tno
	 * 
	 * @return the value of course.Tno
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public String getTno() {
		return tno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column course.Tno
	 * 
	 * @param tno
	 *            the value for course.Tno
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public void setTno(String tno) {
		this.tno = tno;
	}

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}
}