package com.neil.pojo;

public class Sc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sc.Sno
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	private String sno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sc.Cno
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	private String cno;

	private Course course;

	private Student student;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sc.Score
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	private Integer score;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sc.Sno
	 * 
	 * @return the value of sc.Sno
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public String getSno() {
		return sno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sc.Sno
	 * 
	 * @param sno
	 *            the value for sc.Sno
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public void setSno(String sno) {
		this.sno = sno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sc.Cno
	 * 
	 * @return the value of sc.Cno
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public String getCno() {
		return cno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sc.Cno
	 * 
	 * @param cno
	 *            the value for sc.Cno
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public void setCno(String cno) {
		this.cno = cno;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sc.Score
	 * 
	 * @return the value of sc.Score
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sc.Score
	 * 
	 * @param score
	 *            the value for sc.Score
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	public void setScore(Integer score) {
		this.score = score;
	}
}