package com.neil.pojo;

public class Student {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.Sno
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private String sno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.Sname
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private String sname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.password
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.Sex
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.Sdept
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private String sdept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.classe
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private Integer classe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.Sno
	 * @return  the value of student.Sno
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public String getSno() {
		return sno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.Sno
	 * @param sno  the value for student.Sno
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setSno(String sno) {
		this.sno = sno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.Sname
	 * @return  the value of student.Sname
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public String getSname() {
		return sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.Sname
	 * @param sname  the value for student.Sname
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setSname(String sname) {
		this.sname = sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.password
	 * @return  the value of student.password
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.password
	 * @param password  the value for student.password
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.Sex
	 * @return  the value of student.Sex
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.Sex
	 * @param sex  the value for student.Sex
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.Sdept
	 * @return  the value of student.Sdept
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public String getSdept() {
		return sdept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.Sdept
	 * @param sdept  the value for student.Sdept
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setSdept(String sdept) {
		this.sdept = sdept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.classe
	 * @return  the value of student.classe
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public Integer getClasse() {
		return classe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.classe
	 * @param classe  the value for student.classe
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setClasse(Integer classe) {
		this.classe = classe;
	}
}