package com.neil.pojo;

public class Teacher {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.Tno
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private String tno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.tname
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private String tname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.password
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.sex
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	private String sex;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.Tno
	 * @return  the value of teacher.Tno
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public String getTno() {
		return tno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.Tno
	 * @param tno  the value for teacher.Tno
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setTno(String tno) {
		this.tno = tno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.tname
	 * @return  the value of teacher.tname
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public String getTname() {
		return tname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.tname
	 * @param tname  the value for teacher.tname
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setTname(String tname) {
		this.tname = tname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.password
	 * @return  the value of teacher.password
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.password
	 * @param password  the value for teacher.password
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.sex
	 * @return  the value of teacher.sex
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.sex
	 * @param sex  the value for teacher.sex
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}
}