package com.neil.mapper;

import com.neil.pojo.Administrator;

public interface AdministratorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table administrator
	 * 
	 * @mbg.generated Sat Jun 17 21:27:32 CST 2017
	 */
	int deleteByPrimaryKey(String account);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table administrator
	 * 
	 * @mbg.generated Sat Jun 17 21:27:32 CST 2017
	 */
	int insert(Administrator record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table administrator
	 * 
	 * @mbg.generated Sat Jun 17 21:27:32 CST 2017
	 */
	int insertSelective(Administrator record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table administrator
	 * 
	 * @mbg.generated Sat Jun 17 21:27:32 CST 2017
	 */
	Administrator selectByPrimaryKey(String account);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table administrator
	 * 
	 * @mbg.generated Sat Jun 17 21:27:32 CST 2017
	 */
	int updateByPrimaryKeySelective(Administrator record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table administrator
	 * 
	 * @mbg.generated Sat Jun 17 21:27:32 CST 2017
	 */
	int updateByPrimaryKey(Administrator record);
}