package com.neil.mapper;

import java.util.List;

import com.neil.pojo.Course;

public interface CourseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int deleteByPrimaryKey(String cno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int insert(Course record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int insertSelective(Course record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	Course selectByPrimaryKey(String cno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int updateByPrimaryKeySelective(Course record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table course
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int updateByPrimaryKey(Course record);

	List<Course> queryCourse(String sno);

	List<Course> queryTeacherCourse(String tno);
	
	List<Course> selectAll();
}