package com.neil.mapper;

import java.util.HashMap;
import java.util.List;

import com.neil.pojo.Course;
import com.neil.pojo.Sc;

public interface ScMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int deleteByPrimaryKey(Sc key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int insert(Sc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int insertSelective(Sc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	Sc selectByPrimaryKey(Sc key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int updateByPrimaryKeySelective(Sc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sc
	 * 
	 * @mbg.generated Tue May 30 12:49:10 CST 2017
	 */
	int updateByPrimaryKey(Sc record);

	List<Sc> queryScore(String sno);

	List<Sc> queryStudentScore(String tno);

	List<Sc> queryFailStudentScore(String tno);

	List<Sc> queryStudentScoreByScore(String tno);

	List<Sc> queryStudentScoreBySdept(String tno);

	List<Sc> searchScoreByCno(Sc sc);

	List<Sc> searchScoreByCname(Sc sc);

	List<Sc> searchStudentScoreBySno(Sc sc);

	List<Sc> searchStudentScoreBySname(Sc sc);

	HashMap<String,Integer>scoreAvg(Course course);

}