package com.neil.mapper;

import java.util.List;

import com.neil.pojo.Teacher;

public interface TeacherMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	int deleteByPrimaryKey(String tno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	int insert(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	int insertSelective(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	Teacher selectByPrimaryKey(String tno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	int updateByPrimaryKeySelective(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Tue May 30 12:49:10 CST 2017
	 */
	int updateByPrimaryKey(Teacher record);
	
	List<Teacher>selectAll();
}